### PR TITLE
Added DoctrineTokenAuthorizationService

### PR DESCRIPTION
**Pull request by JeroenDeDauw**

### CODE REVIEW

**Comment by JeroenDeDauw** [comment]
Not entirely convinced about this Specify thing yet...

**Comment by KaiNissen** [comment]
What made you introduce Specify? Can you specify?

**Comment by JeroenDeDauw** [comment]
See Gabriels email on grouping tests.

My idea here is to try it out for a bit, and if we decide we don't like it, throw it out again (will not be a lot of work). So far I'm not sold on the thing, but I'd like to give it a bit more of a chance.

**Comment by KaiNissen** [comment]
yes, read that in the meantime

**Pull request merged**
