### PR TITLE
output as expected by client side response handling

### PR DESCRIPTION
**Pull request by KaiNissen**
The output of the `validate-fee` route does not match what is expected by the client-side handler.

### CODE REVIEW

**Comment by KaiNissen** [comment]
no reviewer any time soon, so self-merging this.

**Comment by gbirke** [comment]
Looks good, +2

**Comment by JeroenDeDauw** [comment]
such a no test

**Comment by KaiNissen** [comment]
@JeroenDeDauw I think this is better covered in a browser test, since it's interaction between client-side and server-side code.

**Comment by JeroenDeDauw** [comment]
It'd be nice to have such a test as well. However you still get the usual value from a more local test: you know that the output of the code is as you specified, you have such a specification, and when you refactor the code, you'll notice (unintentional) changes to the behavior.

no-testing-required-it-will-work

PS: found this for usage when the next AB test is requested from the management side:

asian-father-growth-giant

**Pull request merged**
