### PR TITLE
pass proxy dir to StoreFactory

### PR DESCRIPTION
**Pull request by KaiNissen**
This patch requires wmde/FundraisingStore#120 to be merged first. It fixes wmde/fundraising#1187.

### CODE REVIEW

**Comment by JeroenDeDauw** [comment]
+1

**Comment by gbirke** [comment]
@JeroenDeDauw The underlying issue is that autogenerated proxy classes are generated in `/tmp` where they are deleted regularly by the OS. The solution is twofold - move path for proxy classes to the `var` dir and autogenerate the classes on deployment.

Only the first part of the solution (the path) can be unit tested, but I don't know if objects created be the `FunFunFactory` should be tested and where such a test would live.

The second part would be a test for the Ansible deployment playbook and we don't do that at the moment.

**Comment by JeroenDeDauw** [comment]
Hmm sure

**Comment by gbirke** [comment]
A thought - does the directory need to exist or will it be created automatically? Maybe the unit test can force a proxy object to be created while the directory is absent.

**Comment by gbirke** [comment]
This is very hard to test in an automated manner - when manually testing the subscription confirmation manually, the test fails if the classes don't exist.`ConfirmSubscriptionRouteTest` runs without a hitch, regardless of the existence of the proxy classes. 

I've tested the Ansible patch manually to make sure the proxy classes are generated and the confirmation route works. It does, so this can be merged.

**Comment by gbirke** [comment]
One remark about the deployment: After merging this, the checkout of this repo on the deployment server must be updated. I've set it to this branch temporarily to test this PR, but it should be reverted to master.

**Comment by KaiNissen** [comment]
checked out master on the deployment server

**Pull request merged**
