### PR TITLE
Improve default development configuration

### PR DESCRIPTION
**Pull request by gbirke**
Reduce the minimum waiting period between donations and membership
applications to 1 second. This allows for "unlimited" donations and
membership applications without having to clear the cookie in between.

### CODE REVIEW

**Comment by JeroenDeDauw** [comment]
This is development config? The file is named `config.prod.json`...

**Comment by gbirke** [comment]
I'd prefer to keep the test and "prod" configurations separated, otherwise you might accidentally trigger external services when runnnig E2E and you forget to override/disable them in test. 

Dropping the `.prod` suffix would be ok with me.

What do you think about the configuration naming scheme, @aniansson , @timEulitz , @tzhelyazkova ?

**Comment by tzhelyazkova** [comment]
I prefer `config.local.json` because it implies you're not gonna break anything "important". The name `config.json` sounds as "scary" as `config.prod.json` to me.

**Comment by JeroenDeDauw** [comment]
> I'd prefer to keep the test and "prod" configurations separated, otherwise you might accidentally trigger external services when runnnig E2E and you forget to override/disable them in test.

Oh yeah, good point :)

**Pull request merged**
