### PR TITLE
T182405 Validate address input length

### PR DESCRIPTION
**Pull request by gbirke**
Validate address fields with patterns.

### CODE REVIEW

**Comment by wiese** [comment]
We talked about the `addEagerChangeBehavior` for memberships yesterday. Do you think the same logic we found true for donation applies there?

**Comment by gbirke** [comment]
It's not as bad as in the donation form where the city is the last field and the `addEagerChangeBehavior` is the solution to that. But for consistencies sake I can use this PR to add it. But I have to take care that the message does not pup up too early, e.g. while you're in the process of filling out the postcode field which now validates the postcode length.

**Comment by wiese** [comment]
...and the street/house number (T180042).

**Comment by gbirke** [comment]
Rebased for another PR that will be based on this.

**Pull request merged**
