### PR TITLE
Improved DoctrineDonationRepositoryTest

### PR DESCRIPTION
**Pull request by JeroenDeDauw**
Includes a free TRACKING_TRACKING constant and DataData method!

### CODE REVIEW

**Comment by manicki** [comment]
`TRACKING_TRACKING` is cool indeed. However, if alternative names were about to be considered, the value of it is supposed a combination of "campaign code" (I'd also call it a "test code") and "banner code" (campaign codes are skipped in some cases if I remember right, correct?). `TRACKING_CAMPAIGN_AND_BANNER_CODE` is getting verbose. Wouldn't calling it a `TRACKING_CODE` be going too far? That name doesn't explain much either.
So, as in the current donation campaign environment (that is rather unlikely too change I think) particular banners are always bound to campaigns (even if there are same-looking banners in multiple campaigns they have different codes/ids), maybe `TRACKING_BANNER_CODE`? or `TRACKING_BANNER_ID`?

Or maybe just let it be `TRACKING_TRACKING`, I dont know.

**Comment by manicki** [comment]
Just realized that `TRACKING_BANNER_CODE` would not be specific enough. There are other things than banners that link to donation site and are tracked with a `tracking`. E.g. there is a "Spenden Sie jetzt!" link on https://www.wikimedia.de/wiki/Hauptseite and when a person follows it and donates, the donation gets a `tracking` "wikimedia_de_sidebar/Spendenaufruf".
So I am out of ideas. Sorry for elaborating and good luck @KaiNissen @gbirke with coming up with a name for tracking tracking!

**Comment by gbirke** [comment]
Since the key in the data unfortunately really is `tracking` and applies to tracking data, I'm fine with `TRACKING_TRACKING` 😄

**Comment by gbirke** [comment]
@KaiNissen told me he doesn't like it but doesn't care enough. So I'll just mergeMerge it.

**Pull request merged**
