### PR TITLE
redirect from old URLs

### PR DESCRIPTION
**Pull request by KaiNissen**
[phab:T123054](https://phabricator.wikimedia.org/T123054)

### CODE REVIEW

**Comment by JeroenDeDauw** [comment]
+1

**Comment by gbirke** [comment]
Do we need to support any GET/POST parameters for the the `/spenden/?foo==bar` and `/spenden?foo=bar` cases, e.g. for tracking? I know it's legacy support, but still ...

**Comment by KaiNissen** [comment]
I reworked this a little and added support for preserving the query string.

**Comment by gbirke** [comment]
When I tested on my local VM (that uses Nginx) and on the test server, it turned out that we still have to do some server-side rewrite, otherwise the Nginx rules will try to access a nonexisting PHP file.

Did a commit for it in the infrastucture repo.

**Pull request merged**
