### PR TITLE
Shortened names of MembershipApplication cancellation request and response

### PR DESCRIPTION
**Pull request by JeroenDeDauw**
They are namespaced already anyway

### CODE REVIEW

**Comment by KaiNissen** [comment]
Okay, I thought it was some kind of unwritten law to name the request class after the use case it is serving. Let me change `HandlePayPalPaymentNotificationRequest` quickly...

**Comment by JeroenDeDauw** [comment]
Yeah, `NotificationRequest` seems clear enough.

We already derivated (how the smag is this spelled?) from this for at least `DisplayPage` and `AddSubscription`

**Comment by manicki** [comment]
> We already derivated (how the smag is this spelled?) 

derived

**Comment by JeroenDeDauw** [comment]
The one I was thinking about is "deviated"

**Pull request merged**
