### PR TITLE
Small refactoring of composer setup script

### PR DESCRIPTION
**Pull request by bekh6ex**
Didn't actually test it, but in theory should work :smile:

### CODE REVIEW

**Comment by JeroenDeDauw** [comment]
Build failed tho... just restarted it

**Comment by gbirke** [comment]
@bekh6ex This looks good, however our CI keeps failing. Maybe you cloned from a version where our CI was not stable? Could you rebase to current paster and try again?

**Comment by bekh6ex** [comment]
I have no idea why tests are failing...

**Comment by wiese** [comment]
The answer is actually quite simple if we look at the test that fails and think about it.
Anyone (+/-) can create a PR with code changes he defines - one could craft a PR that takes all environment variables in the travis run and sends them to a server he controls, hence "Encrypted environment variables are not available to pull requests from forks due to the security risk of exposing such information to unknown code."

https://docs.travis-ci.com/user/environment-variables/#Defining-encrypted-variables-in-.travis.yml

**Comment by JeroenDeDauw** [comment]
Huh... I'm confoosed.

We already ran into this once long ago and then fixed it by adding this to the test:

```php
		if ( $this->accessKey === '' || $this->projectId === '' ) {
			$this->markTestSkipped( 'Need access key and project id to run MCP system tests' );
		}
```

No longer working though?

**Comment by wiese** [comment]
According to `.travis.yml`'s

    "if [ \"$MCP_ACCESS_KEY\" != \"\" ] && [ \"$MCP_PROJECT_ID\" != \"\" ]; then bash build/travis/createLocalTestConfig.sh > app/config/config.test.local.json; fi"

`config.test.local.json` is never created if the env vars are empty, the checked-in `config.test.json` is used instead, and this contains wrong (non-empty) dummy values that lead to the error.

**Comment by gbirke** [comment]
Closing this, as we're no longer using Vagrant

**Pull request closed without merging**
