### PR TITLE
Added CreditCardService

### PR DESCRIPTION
**Pull request by JeroenDeDauw**
https://phabricator.wikimedia.org/T130186

### CODE REVIEW

**Comment by JeroenDeDauw** [comment]
As part of https://phabricator.wikimedia.org/T130191, the date should stored in `$data['mcp_cc_expiry_date']`

**Comment by KaiNissen** [comment]
The payment provider will provide us with a test account that we can use to write edge-to-edge tests. They also updated their client code library for PHP and fixed a bug that occurs in PHP 7. Example code can be found inside the [library code](https://techdoc.micropayment.de/payment/serviceclient/download/mcp-serviceclient_1_19.zip). Unfortunately there is some Germanness in the example code.

**Comment by KaiNissen** [comment]
Currently the month is stored in two digit format. Not sure, if leaving out the padded '0' can lead to problems when importing our dump to Grün Software's VEWA.

**Comment by JeroenDeDauw** [comment]
It's the responsibility of the persistence service to format the data as required by the persistence.

**Pull request merged**
