### PR TITLE
Add Vagrant environment

### PR DESCRIPTION
**Pull request by gbirke**
Add Vagrantfile that sets up an environment where the fundrasing app can
be run.

### CODE REVIEW

**Comment by JeroenDeDauw** [comment]
Why is this marked WIP? This already works no?

**Comment by gbirke** [comment]
Because the JavaScript and creation of a database stuff is missing. And the PHP service is untested. Also, some explanation/documentation in the the README is needed. I'd rather not have half-finished features in the master branch which will the confuse people who think that using the Vagrantfile is actually a viable option.

**Comment by JeroenDeDauw** [comment]
Tests do not currently run due to:

```
ubuntu@ubuntu-xenial:/vagrant$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - squizlabs/php_codesniffer 2.7.1 requires ext-simplexml * -> the requested PHP extension simplexml is missing from your system.
    - squizlabs/php_codesniffer 2.7.0 requires ext-simplexml * -> the requested PHP extension simplexml is missing from your system.
    - squizlabs/php_codesniffer 2.6.2 requires ext-simplexml * -> the requested PHP extension simplexml is missing from your system.
    - squizlabs/php_codesniffer 2.6.1 requires ext-simplexml * -> the requested PHP extension simplexml is missing from your system.
    - squizlabs/php_codesniffer 2.6.0 requires ext-simplexml * -> the requested PHP extension simplexml is missing from your system.
    - squizlabs/php_codesniffer 2.5.0 requires ext-xmlwriter * -> the requested PHP extension xmlwriter is missing from your system.
    - squizlabs/php_codesniffer 2.5.1 requires ext-xmlwriter * -> the requested PHP extension xmlwriter is missing from your system.
    - squizlabs/php_codesniffer 2.5.1 requires ext-xmlwriter * -> the requested PHP extension xmlwriter is missing from your system.
    - Installation request for squizlabs/php_codesniffer ~2.5 -> satisfiable by squizlabs/php_codesniffer[2.5.0, 2.5.1, 2.6.0, 2.6.1, 2.6.2, 2.7.0, 2.7.1].

  To enable extensions, verify that they are enabled in your .ini files:
    - /etc/php/7.1/cli/php.ini
    - /etc/php/7.1/cli/conf.d/10-mysqlnd.ini
    - /etc/php/7.1/cli/conf.d/10-opcache.ini
    - /etc/php/7.1/cli/conf.d/10-pdo.ini
    - /etc/php/7.1/cli/conf.d/20-calendar.ini
    - /etc/php/7.1/cli/conf.d/20-ctype.ini
    - /etc/php/7.1/cli/conf.d/20-curl.ini
    - /etc/php/7.1/cli/conf.d/20-exif.ini
    - /etc/php/7.1/cli/conf.d/20-fileinfo.ini
    - /etc/php/7.1/cli/conf.d/20-ftp.ini
    - /etc/php/7.1/cli/conf.d/20-gettext.ini
    - /etc/php/7.1/cli/conf.d/20-iconv.ini
    - /etc/php/7.1/cli/conf.d/20-intl.ini
    - /etc/php/7.1/cli/conf.d/20-json.ini
    - /etc/php/7.1/cli/conf.d/20-mysqli.ini
    - /etc/php/7.1/cli/conf.d/20-pdo_mysql.ini
    - /etc/php/7.1/cli/conf.d/20-pdo_sqlite.ini
    - /etc/php/7.1/cli/conf.d/20-phar.ini
    - /etc/php/7.1/cli/conf.d/20-posix.ini
    - /etc/php/7.1/cli/conf.d/20-readline.ini
    - /etc/php/7.1/cli/conf.d/20-shmop.ini
    - /etc/php/7.1/cli/conf.d/20-sockets.ini
    - /etc/php/7.1/cli/conf.d/20-sqlite3.ini
    - /etc/php/7.1/cli/conf.d/20-sysvmsg.ini
    - /etc/php/7.1/cli/conf.d/20-sysvsem.ini
    - /etc/php/7.1/cli/conf.d/20-sysvshm.ini
    - /etc/php/7.1/cli/conf.d/20-tokenizer.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.
```

**Comment by gbirke** [comment]
Maybe you need to add `php7.1-simplexml` and `php7.1-xmlwriter` to `install_packages.sh`?

**Comment by JeroenDeDauw** [comment]
Probably. I suspect this is easy to fix and posted here just as a note where I left the task at.

**Comment by JeroenDeDauw** [comment]
Meh... this is annoying... so if I run composer update on the Vagrant so it has the correct packages there, the lock file on the host gets modified and ends up in the git change list.

**Comment by JeroenDeDauw** [comment]
This is ready for merge IMO. It allows you to run the PHPUnit tests. While it's nice to be able to do more stuff, what is there works and is useful. We can step-by-step add additional things.

Going to leave the node and npm installation to @gbirke since presumably some magical install thinghy needs to be used rather than apt-get which gives ancient versions.

**Comment by gbirke** [comment]
@JeroenDeDauw You're not supposed to run `composer update` inside the VM, only `composer install` which will use the lock file to check for the versions to install and up/downgrade the packages accordingly. When to branches have different lock file versions, run `composer install` after changing the branch.

**Comment by JeroenDeDauw** [comment]
I ran into a case where `composer install` failed, which is why I ran `update`. Perhaps that was caused by the missing packages though, I don't recall.

**Pull request merged**
