### PR TITLE
T162438: Membership fee payments by paypal

### PR DESCRIPTION
**Pull request by KaiNissen**
This PR requires wmde/fundraising-frontend-content#21. It is part of [phab:T162438](https://phabricator.wikimedia.org/T162438) and adds the changes to the membership application confirmation mail templates as defined in wmde/fundraising#1083.

### CODE REVIEW

**Comment by JeroenDeDauw** [comment]
+0.85

**Comment by KaiNissen** [comment]
I cherry-picked 04a386c052d2a3d712ae62365dbea65bdd0874ba from #901 and removed non-applicable payment type options as also done in 04120a1d010ccf85beb7b486cbec4658472bc608 of #909.

**Comment by JeroenDeDauw** [comment]
> There were 9 errors:
> 
> 1) WMDE\Fundraising\Frontend\Tests\EdgeToEdge\Routes\ApplyForMembershipRouteTest::testGivenValidRequest_applicationIsPersisted
> 
> Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("An exception occurred rendering 'membership_application_confirmation/payment_notice_direct_debit'").
> 
> Caused by
> 
> Twig_Error_Loader: Unable to find template "membership_application_confirmation/payment_notice_direct_debit.twig" (looked into: /home/travis/build/wmde/FundraisingFrontend/src/Factories/../../vendor/wmde/fundraising-frontend-content/i18n/de_DE/mail, /home/travis/build/wmde/FundraisingFrontend/src/Factories/../../vendor/wmde/fundraising-frontend-content/i18n/de_DE/shared).

**Comment by wiese** [comment]
* committed GeneratedMailTemplates for changed test cases into repo
  * some test cases where renamed, so the tests did not break (no diff)
  * some where added, so the tests did not break (no diff either)
* made logic fall under test coverage (by loading different tpls from content)

**Comment by KaiNissen** [comment]
added another commit to use a translatable message as the `item_name` passed to PayPal

**Pull request merged**
