### PR TITLE
Add preliminary state graph

### PR DESCRIPTION
**Pull request by gbirke**
Added state graph as Graphviz file.

The description of states is not complete and also needs the
additional actions when moderated/deleted donations are booked
externally and the guard clauses when a state is restored in the backend (see
https://github.com/wmde/fundraising-backend/blob/bf379296aef2a5ee702aacdc4c91261db6bfc065/application/model/Donation.php#L50-L73
for that).

### CODE REVIEW

**Comment by JeroenDeDauw** [comment]
+1. How to best view without installing fancy stuff?

**Comment by gbirke** [comment]
http://www.webgraphviz.com/

**Comment by JeroenDeDauw** [comment]
Cool.

External Incomplete is a possible starting state right? Perhaps the starting states should be indicated somehow? Cause now it kinda looks like you cannot get to any of the external states without first going through moderation.

**Comment by gbirke** [comment]
Added double lines to mark initial states

**Comment by JeroenDeDauw** [comment]
Merged it now. Probably good if @KaiNissen does a double check though.

**Comment by KaiNissen** [comment]
It is actually the result of @gbirke and me talking about this. I do approve.

**Pull request merged**
