### PR TITLE
T180431 Opt out of donation receipts

### PR DESCRIPTION
**Pull request by wiese**
Opt out of donation receipt for donation.

### CODE REVIEW

**Comment by wiese** [comment]
virtualbox_ie10 - win7_01_12_2017_09_43_42

**Comment by gbirke** [comment]
I changed the CSS to use flex again (with `flex-direction: column;`) and changed the `width` and `display` settings for the label.

**Comment by wiese** [comment]
@gbirke aed4431 does resolve the IE10 checkbox issue but destroys the vertical alignment of labels with their radio buttons (current Firefox, Chrome, IE10). As this seems to be on the right trail, can we differentiate `[type="radio"] + label` and `[type="checkbox"] + label`? Maybe not elegant but effective in all our current scenarios?!

**Comment by JeroenDeDauw** [comment]
Rebased

How are you testing this against IE?

**Comment by gbirke** [comment]
https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/

**Comment by wiese** [comment]
Very cool. This looks fine now on all the mentioned browsers.

**Pull request merged**
