### PR TITLE
changed AddSubscriptionResponse to generic ValidationResponse

### PR DESCRIPTION
**Pull request by KaiNissen**
The response model is quite generic for validation requests, and could be reused by other use case implementations.

### CODE REVIEW

**Comment by JeroenDeDauw** [comment]
When doing this, we should be careful to not add usecase specific things to the generic thing. If there is need for usecase specific stuff, it's time to move away from the generic solution.

**Comment by KaiNissen** [comment]
Sure, but we can still derive from it, I guess.

**Comment by JeroenDeDauw** [comment]
+1

**Comment by gbirke** [comment]
I'm also not sure if this is a case of premature generalization, but will merge it none the less.

**Pull request merged**
